apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-migrate-{{ .Release.Revision }}
  labels:
    {{- include "crypto-prices.labels" . | nindent 4 }}
    app.kubernetes.io/component: migration
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 5
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-migrate
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          command: ["dumb-init", "--", "./docker-entrypoint.sh", "migrate"]
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: crypto-prices-secret
                  key: db-password
            - name: POSTGRES_PRISMA_URL
              value: {{ printf "postgres://%s:$(DB_PASSWORD)@%s-postgresql:5432/%s?schema=public" .Values.app.config.dbUser .Release.Name .Values.app.config.dbName | quote }}
